"""Wire protocol for `dictation.v1` and `dictation.v2`.

See docs/api/dictation-ws-v1.md and docs/api/dictation-ws-v2.md.
"""

from .codec import (
    PROTOCOL_VERSION,
    SUBPROTOCOL,
    SUBPROTOCOL_V2,
    BadMessageError,
    decode_binary,
    decode_text,
    encode_server,
    negotiate_subprotocol,
    subprotocol_for_version,
)
from .error_catalogue import ErrorCode
from .messages import (
    PROTOCOL_VERSION_V1,
    PROTOCOL_VERSION_V2,
    AudioFrame,
    ClientMessage,
    ClientMessageV2,
    EndSession,
    Error,
    Final,
    FinalV2,
    Heartbeat,
    Partial,
    PartialV2,
    Pause,
    RefreshToken,
    Resume,
    RetransmitRange,
    ServerMessage,
    ServerMessageV2,
    SessionStarted,
    SessionStartedV2,
    SessionTerminated,
    SetSpeakerMapping,
    SpeakerMappingUpdated,
    StartSession,
    StartSessionV2,
    SwitchSection,
    TokenExpiring,
    TokenTiming,
    VoiceCommand,
    WarningMessage,
)

__all__ = [
    "AudioFrame",
    "BadMessageError",
    "ClientMessage",
    "ClientMessageV2",
    "EndSession",
    "Error",
    "ErrorCode",
    "Final",
    "FinalV2",
    "Heartbeat",
    "PROTOCOL_VERSION",
    "PROTOCOL_VERSION_V1",
    "PROTOCOL_VERSION_V2",
    "Partial",
    "PartialV2",
    "Pause",
    "RefreshToken",
    "Resume",
    "RetransmitRange",
    "SUBPROTOCOL",
    "SUBPROTOCOL_V2",
    "ServerMessage",
    "ServerMessageV2",
    "SessionStarted",
    "SessionStartedV2",
    "SessionTerminated",
    "SetSpeakerMapping",
    "SpeakerMappingUpdated",
    "StartSession",
    "StartSessionV2",
    "SwitchSection",
    "TokenExpiring",
    "TokenTiming",
    "VoiceCommand",
    "WarningMessage",
    "decode_binary",
    "decode_text",
    "encode_server",
    "negotiate_subprotocol",
    "subprotocol_for_version",
]
