/**
 * A generated line's key — the server's rule, ported (Summary Engine v2, Q5).
 *
 * The note shows lines; the evidence behind each lives in a row keyed by
 * `lines.key_of(lines.strip_marker(line))` in note-service: the marker off,
 * an "Owner:" prefix and a "— due" tail stripped (so fixing an owner or a
 * date keeps the line's evidence), the rest normalised and hashed —
 * sha256, first 16 hex characters. The client hashes the line it displays
 * the same way to find its row: no positional mapping, nothing to drift.
 *
 * Both test suites read `web/tests/fixtures/item-keys.json`, generated by
 * `scripts/dev/item_key_fixtures.py` from the Python side.
 */

// lines.py _MARKER
const MARKER = /^([\s>]*(?:[-–—•*·▪◦●○]+|\(?(?:\d{1,2}|[a-zA-Z])[.)])\s*)/;
// action_items.py _BULLET, _OWNER, _DUE_DASH, _DUE_WORD
const BULLET = /^[\s\-•*·▪◦]*(?:\d{1,2}[.)]\s*)?[\s\-•*·]*/;
const OWNER = /^([^:—–-]{1,60}?):(?!\/\/)\s*(\S.*)$/;
const DUE_DASH = /^(.+?)\s+[—–-]\s*(?:(?:by|due|until|до|bis)\s+)?(.+?)\s*$/i;
const DUE_WORD = /^(.+?)\s+(?:by|due|until|до|bis)\s+(.+?)\s*$/i;
const MAX_TEXT = 500;

/** lines.strip_marker → the content without its list marker. */
export function stripMarker(line: string): string {
  const m = MARKER.exec(line);
  return (m ? line.slice(m[0].length) : line).trim();
}

/** action_items.normalise_text */
export function normaliseText(text: string): string {
  return text.replace(/\s+/g, " ").trim().replace(/[.;,]+$/, "").trim().toLowerCase();
}

function splitDue(rest: string): string {
  for (const pattern of [DUE_DASH, DUE_WORD]) {
    const m = pattern.exec(rest);
    if (m && (m[2] ?? "").trim()) return (m[1] ?? "").trim();
  }
  return rest.trim();
}

/** lines.key_of(content) — content with the marker already off. */
export function keyOf(content: string): string {
  let line = content.replace(BULLET, "").trim();
  if (!line) return sha256Hex(normaliseText(content)).slice(0, 16);
  const owner = OWNER.exec(line);
  if (owner && (owner[1] ?? "").trim().split(/\s+/).length <= 4) line = owner[2] ?? "";
  const body = splitDue(line).slice(0, MAX_TEXT);
  return sha256Hex(normaliseText(body)).slice(0, 16);
}

/** The key of a line as it is displayed, marker and all. */
export function lineKey(line: string): string {
  return keyOf(stripMarker(line));
}

// ── sha256, synchronous (rendering cannot await crypto.subtle) ──────

const K = new Uint32Array([
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
  0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
  0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
  0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
  0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
  0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
  0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
  0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
]);

export function sha256Hex(text: string): string {
  const bytes = new TextEncoder().encode(text);
  const bitLength = bytes.length * 8;
  const padded = new Uint8Array(((bytes.length + 9 + 63) >> 6) << 6);
  padded.set(bytes);
  padded[bytes.length] = 0x80;
  const view = new DataView(padded.buffer);
  view.setUint32(padded.length - 8, Math.floor(bitLength / 2 ** 32));
  view.setUint32(padded.length - 4, bitLength >>> 0);
  const h = new Uint32Array([
    0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
  ]);
  const w = new Uint32Array(64);
  const rotr = (x: number, n: number) => (x >>> n) | (x << (32 - n));
  for (let offset = 0; offset < padded.length; offset += 64) {
    for (let i = 0; i < 16; i++) w[i] = view.getUint32(offset + i * 4);
    for (let i = 16; i < 64; i++) {
      const a = w[i - 15] as number;
      const b = w[i - 2] as number;
      const s0 = rotr(a, 7) ^ rotr(a, 18) ^ (a >>> 3);
      const s1 = rotr(b, 17) ^ rotr(b, 19) ^ (b >>> 10);
      w[i] = ((w[i - 16] as number) + s0 + (w[i - 7] as number) + s1) >>> 0;
    }
    let [a, b, c, d, e, f, g, hh] = Array.from(h) as [number, number, number, number, number, number, number, number];
    for (let i = 0; i < 64; i++) {
      const S1 = rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25);
      const ch = (e & f) ^ (~e & g);
      const t1 = (hh + S1 + ch + (K[i] as number) + (w[i] as number)) >>> 0;
      const S0 = rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22);
      const maj = (a & b) ^ (a & c) ^ (b & c);
      const t2 = (S0 + maj) >>> 0;
      hh = g;
      g = f;
      f = e;
      e = (d + t1) >>> 0;
      d = c;
      c = b;
      b = a;
      a = (t1 + t2) >>> 0;
    }
    h[0] = ((h[0] as number) + a) >>> 0;
    h[1] = ((h[1] as number) + b) >>> 0;
    h[2] = ((h[2] as number) + c) >>> 0;
    h[3] = ((h[3] as number) + d) >>> 0;
    h[4] = ((h[4] as number) + e) >>> 0;
    h[5] = ((h[5] as number) + f) >>> 0;
    h[6] = ((h[6] as number) + g) >>> 0;
    h[7] = ((h[7] as number) + hh) >>> 0;
  }
  return Array.from(h, (x) => x.toString(16).padStart(8, "0")).join("");
}
