"""note-service configuration."""

from __future__ import annotations

import os
from collections.abc import Mapping
from typing import Annotated, Literal

from pydantic import Field
from pydantic_settings import BaseSettings, NoDecode, SettingsConfigDict

from secret import Secret

# ``Secret[str]`` is a generic, so pydantic-settings classes it as a complex
# type and json.loads() the raw env value — any plain string (including "")
# blows up with a JSONDecodeError before the field is ever validated. NoDecode
# hands the raw string straight to Secret's validator. Every Secret field fed
# from the environment must use this alias.
SecretStrEnv = Annotated[Secret[str], NoDecode]


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env.local",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    service_name: str = "note-service"
    environment: str = Field(default="development", alias="ENVIRONMENT")
    log_level: str = Field(default="INFO", alias="LOG_LEVEL")
    testing: bool = Field(default=False, alias="TESTING")

    otel_exporter_otlp_endpoint: str = Field(
        default="http://localhost:4317", alias="OTEL_EXPORTER_OTLP_ENDPOINT"
    )
    otel_sdk_disabled: bool = Field(default=False, alias="OTEL_SDK_DISABLED")

    auth_issuer: str = Field(
        default="http://localhost:8088/realms/notes",
        alias="AUTH_ISSUER",
    )
    auth_jwks_url: str = Field(
        default="http://localhost:8088/realms/notes/protocol/openid-connect/certs",
        alias="AUTH_JWKS_URL",
    )
    auth_audience: str = Field(default="mdx-api", alias="AUTH_AUDIENCE")
    # FND-1 / ADR-0047: the complete list of issuers this service trusts,
    # as JSON — `[{"issuer": …, "jwks_url": …, "audience": …}, …]`. The
    # token's own `iss` selects which entry verifies it. Unset (the
    # default) means the three values above build a one-element list, so
    # a deployment that has not been migrated behaves exactly as before.
    auth_issuers_json: str = Field(default="", alias="AUTH_ISSUERS_JSON")
    auth_clock_skew_seconds: int = Field(default=30, alias="AUTH_CLOCK_SKEW_SECONDS")

    # ── CORS (SPA integration) ──────────────────────────────────────────
    # Comma-separated browser origins allowed to call this service WITH
    # credentials (the HttpOnly refresh cookie). Must be explicit origins —
    # never "*" — because allow_credentials=True forbids the wildcard. Mirror
    # of the auth-service allow-list (sprint A3).
    cors_allowed_origins: str = Field(
        default="http://localhost:5173,http://127.0.0.1:5173,http://localhost:4173,http://127.0.0.1:4173",
        alias="CORS_ALLOWED_ORIGINS",
    )

    @property
    def cors_origins_list(self) -> list[str]:
        return [o.strip() for o in self.cors_allowed_origins.split(",") if o.strip()]

    db_app_role_dsn: str = Field(
        default="postgresql://app_role:app_role@localhost:5432/notes",
        alias="DB_APP_ROLE_DSN",
    )
    db_audit_writer_dsn: str = Field(
        default="postgresql://audit_writer:audit_writer@localhost:5432/notes",
        alias="DB_AUDIT_WRITER_DSN",
    )
    db_pool_min_size: int = Field(default=1, alias="DB_POOL_MIN_SIZE")
    db_pool_max_size: int = Field(default=8, alias="DB_POOL_MAX_SIZE")

    # Sprint-12 notification event bus (ADR-0029).
    redis_url: str = Field(default="redis://localhost:6379/0", alias="REDIS_URL")
    # Set false to stop emitting entirely — the escape hatch if a
    # notification storm ever needs to be cut off at the source (E1).
    notifications_enabled: bool = Field(default=True, alias="MDX_NOTIFICATIONS_ENABLED")

    # In-process TTLCache for templates
    template_cache_maxsize: int = Field(default=5000, alias="MDX_TEMPLATE_CACHE_MAXSIZE")
    template_cache_ttl_seconds: int = Field(default=60, alias="MDX_TEMPLATE_CACHE_TTL_SECONDS")

    # Issuing organisation printed on the exported PDF (M1·A3).
    pdf_issuer_name: str = Field(default="Notes AI", alias="MDX_PDF_ISSUER_NAME")

    # ── Sprint 19: recipient links + the shared page's product header ──
    # The product name in "Meeting summary generated by {brand}. Create
    # your own workspace free." on every shared page. A setting, not a
    # constant, so the brand can change without a release.
    product_brand_name: str = Field(default="Notes AI", alias="MDX_PRODUCT_BRAND_NAME")
    # Recipient links expire by default; public links (0016) still do not.
    recipient_link_default_days: int = Field(default=90, alias="MDX_RECIPIENT_LINK_DEFAULT_DAYS")
    # Abuse caps on the anonymous /v1/shared/* surface (domain/public_rate_limit).
    # Fail-open: a Redis outage must not take every client-facing page down.
    shared_rl_ip_per_minute: int = Field(default=60, alias="MDX_SHARED_RL_IP_PER_MINUTE")
    shared_rl_link_per_hour: int = Field(default=300, alias="MDX_SHARED_RL_LINK_PER_HOUR")
    shared_rl_cta_per_hour: int = Field(default=20, alias="MDX_SHARED_RL_CTA_PER_HOUR")
    # Comma-separated CIDRs whose X-Forwarded-For is believed (same name
    # and rule as auth-service / libs/ratelimit). Empty: the TCP peer is
    # the client — behind an untrusted proxy every reader shares one bucket.
    trusted_proxy_cidrs: str = Field(default="", alias="TRUSTED_PROXY_CIDRS")
    # ── Sprint 22: the product sends recipient links ────────────────────
    # Where the anonymous API is reachable from a recipient's mail client;
    # the unsubscribe link in every recipient mail is built from it.
    api_public_base_url: str = Field(
        default="http://localhost:8006", alias="MDX_API_PUBLIC_BASE_URL"
    )
    # Sends per link, per sender and per workspace, per day.
    share_mail_link_per_day: int = Field(default=3, alias="MDX_SHARE_MAIL_LINK_PER_DAY")
    share_mail_user_per_day: int = Field(default=50, alias="MDX_SHARE_MAIL_USER_PER_DAY")
    share_mail_tenant_per_day: int = Field(default=200, alias="MDX_SHARE_MAIL_TENANT_PER_DAY")
    # Pepper for the opt-out hash (hex). The dev default is NOT a secret;
    # rotating it orphans every existing suppression row.
    share_mail_suppression_pepper_hex: str = Field(
        default="6d64782d6465762d73686172652d6d61696c2d7065707065722d3030303030",
        alias="MDX_SHARE_MAIL_SUPPRESSION_PEPPER_HEX",
    )
    # ── Sprint 23: GA flags, verification, retention ────────────────────
    # Master switch for the loop: off → no recipient/public links can be
    # created and the anonymous page answers 404 for recipient links.
    external_sharing_enabled: bool = Field(default=True, alias="MDX_EXTERNAL_SHARING_ENABLED")
    # Off → the page reads but nobody can confirm/dispute/flag.
    recipient_actions_enabled: bool = Field(default=True, alias="MDX_RECIPIENT_ACTIONS_ENABLED")
    # Recipient one-time codes (policy `verified_recipients_required`).
    share_otp_ttl_seconds: int = Field(default=600, alias="MDX_SHARE_OTP_TTL_SECONDS")
    share_otp_max_attempts: int = Field(default=5, alias="MDX_SHARE_OTP_MAX_ATTEMPTS")
    # Links expired longer than this lose responses, address and codes.
    share_retention_days: int = Field(default=30, alias="MDX_SHARE_RETENTION_DAYS")
    # ── Sprint 20: recipient responses ──────────────────────────────────
    # Writes per link per hour on the anonymous page.
    shared_rl_write_per_hour: int = Field(default=60, alias="MDX_SHARED_RL_WRITE_PER_HOUR")
    # The author is told once per link per this many seconds — a recipient
    # confirming five items is one event, not five.
    response_notify_debounce_s: int = Field(default=600, alias="MDX_RESPONSE_NOTIFY_DEBOUNCE_S")
    # The action-item extractor. `rules` is the deterministic parser and
    # the only value this sprint; the seam exists for a model later.
    action_item_extractor: Literal["rules"] = Field(
        default="rules", alias="MDX_ACTION_ITEM_EXTRACTOR"
    )

    # Sprint 13: typed-field extraction at draft assembly (ADR-0028).
    # Fail-open — an unreachable nlp-service costs proposals, not drafts.
    nlp_service_base_url: str = Field(
        default="http://localhost:8005", alias="MDX_NLP_SERVICE_BASE_URL"
    )

    # asr-service base URL — create-from-transcript fetches the
    # completed job's transcript from there, forwarding the caller's JWT.
    asr_service_base_url: str = Field(default="http://localhost:8001", alias="ASR_SERVICE_BASE_URL")

    # ── "Ask this note" (libs/models chat provider, ADR-0046) ──────────
    # The registry in config/models.yaml decides which backend answers
    # (dev: the Mac's Ollama; staging/prod: the EU endpoint). Resolved
    # on first use, so a Mac without a model server still serves notes.
    models_config: str = Field(default="config/models.yaml", alias="MODELS_CONFIG")
    # Registry env name: dev | test | staging | prod. Derived from
    # ENVIRONMENT when unset (development→dev, production→prod).
    models_env: str = Field(default="", alias="ENV")
    ask_max_tokens: int = Field(default=700, alias="MDX_ASK_MAX_TOKENS")
    # How much of the note + transcript goes into the prompt (characters).
    ask_context_chars: int = Field(default=60_000, alias="MDX_ASK_CONTEXT_CHARS")

    @staticmethod
    def registry_environ() -> Mapping[str, str]:
        """The mapping ``${VAR}`` placeholders in config/models.yaml resolve
        from — here because config.py is the one module allowed to read the
        process environment (check-no-os-environ gate)."""
        return os.environ

    def registry_env(self) -> str:
        if self.models_env:
            return self.models_env
        if self.testing:
            return "test"
        return {
            "development": "dev",
            "production": "prod",
            "test": "test",
            "staging": "staging",
        }.get(self.environment, self.environment)

    # ── Note synthesis (spec item 1) ──────────────────────────────────
    # "mock" (default) is the deterministic offline engine — no external
    # LLM, no note content leaving the box. "anthropic" wires the production stub
    # (Claude Opus 4.x, model id below); enabling it requires implementing
    # the real client AND a compliance sign-off.
    synthesis_provider: Literal["mock", "anthropic"] = Field(
        default="mock", alias="MDX_SYNTHESIS_PROVIDER"
    )
    synthesis_model: str = Field(default="claude-opus-4-8", alias="MDX_SYNTHESIS_MODEL")

    # ── Sprint 15: audio replay (ADR-0037) ──────────────────────────────
    # Clip creation decrypts session/batch audio, slices, re-encodes and
    # serves it from an authenticated stream — note-service therefore
    # gets the same S3+crypto wiring dictation-service has (same env
    # names, so compose blocks are copy-paste).
    db_crypto_writer_dsn: str = Field(
        default="postgresql://crypto_writer:crypto_writer@localhost:5432/notes",
        alias="DB_CRYPTO_WRITER_DSN",
    )
    master_key_path: str = Field(default="/etc/mdx/master.key", alias="MDX_MASTER_KEY_PATH")

    # ── Master-key provider (sprint 16, ADR-0011 KMS swap) ───────────────
    # 'file' (dev default — behaviour identical to pre-sprint-16) or
    # 'vault' (Vault Transit; fail-closed startup probe). With 'vault', the
    # file at master_key_path — if present — stays live as a read-only
    # fallback for rows not yet re-wrapped (scripts/kms/rewrap-tenant-keks.py).
    master_key_provider: str = Field(default="file", alias="MDX_MASTER_KEY_PROVIDER")
    vault_addr: str = Field(default="http://localhost:8200", alias="MDX_VAULT_ADDR")
    vault_token: SecretStrEnv = Field(default_factory=lambda: Secret(""), alias="MDX_VAULT_TOKEN")
    vault_transit_key: str = Field(default="mdx-master", alias="MDX_VAULT_TRANSIT_KEY")
    vault_transit_mount: str = Field(default="transit", alias="MDX_VAULT_TRANSIT_MOUNT")
    s3_endpoint: str = Field(default="http://localhost:9000", alias="S3_ENDPOINT")
    s3_region: str = Field(default="us-east-1", alias="S3_REGION")
    s3_access_key: str = Field(default="minioadmin", alias="S3_ACCESS_KEY")
    s3_secret_key: str = Field(default="minioadmin", alias="S3_SECRET_KEY")
    s3_use_ssl: bool = Field(default=False, alias="S3_USE_SSL")
    s3_audio_bucket: str = Field(default="mdx-audio", alias="S3_AUDIO_BUCKET")
    s3_transcripts_bucket: str = Field(default="mdx-transcripts", alias="S3_TRANSCRIPTS_BUCKET")
    # Ephemeral clip derivatives: 1-day bucket ILM backstop; the REAL
    # lifetime is the 5-minute Redis registry + token TTL below.
    s3_clips_bucket: str = Field(default="mdx-audio-clips", alias="S3_CLIPS_BUCKET")
    object_store_disabled: bool = Field(default=False, alias="MD_OBJECT_STORE_DISABLED")

    # HMAC key for clip download tokens (DSAR download-token idiom,
    # ADR-0028): hex-encoded, dev default is NOT a secret. Rotate freely —
    # tokens live 5 minutes.
    clip_token_hmac_key_hex: str = Field(
        default="6d64782d6465762d636c69702d746f6b656e2d6b65792d3030303030303030",
        alias="MDX_CLIP_TOKEN_HMAC_KEY_HEX",
    )
    clip_token_ttl_seconds: int = Field(default=300, alias="MDX_CLIP_TOKEN_TTL_SECONDS")
    # HMAC key that turns a share-link row id into the public token
    # (domain/share_tokens). Hex-encoded; the dev default is NOT a secret.
    # Rotating it invalidates every public link in the deployment.
    share_link_hmac_key_hex: str = Field(
        default="6d64782d6465762d73686172652d6c696e6b2d6b65792d3030303030303030",
        alias="MDX_SHARE_LINK_HMAC_KEY_HEX",
    )
    clip_max_span_ms: int = Field(default=60_000, alias="MDX_CLIP_MAX_SPAN_MS")
    clip_pad_ms: int = Field(default=300, alias="MDX_CLIP_PAD_MS")
    clips_per_user_per_hour: int = Field(default=30, alias="MDX_CLIPS_PER_USER_PER_HOUR")
    ffmpeg_path: str = Field(default="ffmpeg", alias="MDX_FFMPEG_PATH")

    # ── In-process scheduler (sprint 16, ADR-0041) ──────────────────────
    # Hosts the idle-draft cleanup loop. Off in dev (run the CLI when you
    # need it); production flips MDX_BACKGROUND_JOBS. Interval default =
    # daily; the job is idempotent, so shorter intervals are safe.
    background_jobs_enabled: bool = Field(default=False, alias="MDX_BACKGROUND_JOBS")
    background_jobs_interval_s: float = Field(
        default=86400.0, alias="MDX_BACKGROUND_JOBS_INTERVAL_S"
    )
    # Draft-idleness threshold (spec §4.4 / docs/runbooks/notes.md: 30d).
    idle_draft_days: int = Field(default=30, alias="MDX_IDLE_DRAFT_DAYS")

    # ── Calendar connections (0019) ──────────────────────────────────────
    # Google OAuth client for the read-only calendar connection behind the
    # home page's "Coming up" list. Empty client id = feature off: reads
    # answer ``available: false`` and connect answers 503. Create the
    # client in Google Cloud Console (OAuth 2.0 Client ID, "Web
    # application") with the redirect URI below as an authorised redirect.
    google_calendar_client_id: str = Field(default="", alias="GOOGLE_CALENDAR_CLIENT_ID")
    google_calendar_client_secret: SecretStrEnv = Field(
        default_factory=lambda: Secret(""), alias="GOOGLE_CALENDAR_CLIENT_SECRET"
    )
    # Must be THIS service's public callback URL, exactly as registered
    # at Google (scheme, host, port and path all count).
    google_calendar_redirect_uri: str = Field(
        default="http://localhost:8006/v1/calendar/google/callback",
        alias="GOOGLE_CALENDAR_REDIRECT_URI",
    )
    # HMAC key that signs the OAuth ``state`` (domain/calendar_state).
    # Hex-encoded; the dev default is NOT a secret. Rotating it only
    # invalidates sign-ins that are mid-flight (15 minutes).
    calendar_state_hmac_key_hex: str = Field(
        default="6d64782d6465762d63616c656e6461722d73746174652d6b65792d30303030",
        alias="MDX_CALENDAR_STATE_HMAC_KEY_HEX",
    )
    # Where the callback may send the browser afterwards, on top of the
    # CORS origins (the web app) and the Mac app's ``notesai://`` scheme.
    # Comma-separated URL prefixes.
    calendar_return_to_extra: str = Field(default="", alias="MDX_CALENDAR_RETURN_TO_EXTRA")

    @property
    def calendar_return_to_prefixes(self) -> list[str]:
        extra = [p.strip() for p in self.calendar_return_to_extra.split(",") if p.strip()]
        return [*self.cors_origins_list, "notesai://", *extra]

    # ── Outbound mail (sharing a note by e-mail) ────────────────────────
    # "Send" in the share modal delivers a branded HTML mail from the
    # server. It replaces the old `mailto:` hand-off, which opened
    # whatever the desktop mail client had lying around and put the
    # link in an unstyled draft the sender had to send themselves.
    #
    # `mock` captures in memory and refuses to run in production; `smtp`
    # talks to Mailpit in dev and the real relay in prod. Same env name
    # as auth-service so one deployment-wide switch flips both.
    email_provider: str = Field(default="mock", alias="MDX_EMAIL_PROVIDER")
    note_smtp_host: str = Field(default="localhost", alias="MDX_NOTE_SMTP_HOST")
    note_smtp_port: int = Field(default=1025, alias="MDX_NOTE_SMTP_PORT")
    note_smtp_use_tls: bool = Field(default=False, alias="MDX_NOTE_SMTP_USE_TLS")
    note_smtp_username: str = Field(default="", alias="MDX_NOTE_SMTP_USERNAME")
    # Google Workspace has refused plain account passwords for SMTP since
    # 2024 — this must be a 16-character App Password. The symptom of
    # getting it wrong is `535-5.7.8 Username and Password not accepted`.
    note_smtp_password: SecretStrEnv = Field(
        default_factory=lambda: Secret(""), alias="MDX_NOTE_SMTP_PASSWORD"
    )
    note_email_from: str = Field(default="notes@notes-ai.local", alias="MDX_NOTE_EMAIL_FROM")
    note_email_from_name: str = Field(default="Notes AI", alias="MDX_NOTE_EMAIL_FROM_NAME")
    # Replies go to the person who shared, not to us — set per-send.
    # This is only the fallback when the sharer has no address on file.
    note_email_reply_to: str = Field(
        default="notes@notes-ai.local", alias="MDX_NOTE_EMAIL_REPLY_TO"
    )
    # SPA origin the mailed links point at. A share mail is only useful
    # if it lands on the app the recipient actually runs.
    app_base_url: str = Field(default="http://localhost:5173", alias="MDX_APP_BASE_URL")
    # A hung relay must not hold an HTTP worker until the client gives up.
    share_email_timeout_s: float = Field(default=15.0, alias="MDX_SHARE_EMAIL_TIMEOUT_S")
    # Per request, and per sender per hour. The second is the one that
    # matters: a share endpoint that mails anywhere is a spam relay
    # wearing our From address.
    share_email_max_recipients: int = Field(default=10, alias="MDX_SHARE_EMAIL_MAX_RECIPIENTS")
    share_emails_per_user_per_hour: int = Field(
        default=60, alias="MDX_SHARE_EMAILS_PER_USER_PER_HOUR"
    )
    # How much of the sharer's own words to carry. Long enough for a
    # paragraph of context, short enough that the mail stays a pointer.
    share_email_max_message_chars: int = Field(
        default=1000, alias="MDX_SHARE_EMAIL_MAX_MESSAGE_CHARS"
    )

    # ── Session revocation check (sprint 16) ────────────────────────────
    # When on, current_user rejects tokens whose sid/sub is on the Redis
    # denylist that auth-service pushes on logout/deactivation. Fail-OPEN
    # on Redis outage (ADR-0041). Same env name across the fleet; off in dev.
    session_revocation_enabled: bool = Field(default=False, alias="MDX_SESSION_REVOCATION_ENABLED")

    @property
    def is_production(self) -> bool:
        # Staging counts: a staging deployment that silently swallowed
        # share mail would prove nothing about the one that matters.
        return self.environment in {"production", "staging"}


settings = Settings()
