"""The letters' two rasterised marks: the wordmark and the hero headline.

Generated by tools/render_mail_images.py and committed as artefacts — see
that file for why the display type is an image at all (Gmail and Outlook
strip `@font-face`, so Galgo had never once rendered) and why only these two
things are images while every other line stays live text.

They travel as `cid:` related parts. Nothing here reaches a network: an image
hosted at the public origin would reintroduce the exact dependency that left
the fonts unrendered, and would turn every read into a request against our own
domain — a tracking pixel we did not set out to build.

Read once at import and held: thirteen PNGs come to ~65 KB, the delivery
worker asks for one on every send, and re-reading a committed file per email
is I/O in the middle of a transaction that holds an outbox row.
"""

from __future__ import annotations

import logging
import struct
from dataclasses import dataclass
from functools import cache
from pathlib import Path

IMAGE_DIR = Path(__file__).parent / "mail_images"

logger = logging.getLogger(__name__)

# The value in `cid:` in the template and in Content-ID on the part. Domain-ish
# suffixes because RFC 2392 wants a globally unique token; these never leave
# the message, so the domain need only be ours and stable.
WORDMARK_CID = "wordmark@klarnote.mail"
HEADLINE_CID = "headline@klarnote.mail"

# Rendered at 2× (tools/render_mail_images.py SCALE) and published at 1×.
SCALE = 2


@dataclass(frozen=True, slots=True)
class MailImage:
    cid: str
    filename: str
    data: bytes
    width: int
    """CSS pixels — the intrinsic width halved, because the raster is 2×."""
    height: int


def _png_size(data: bytes) -> tuple[int, int]:
    """Width and height out of the IHDR chunk.

    Sixteen bytes of struct rather than a Pillow import: the service image
    ships no imaging library, and it should not gain one to read two integers
    out of a file this repository generated itself.
    """
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("not a PNG")
    width, height = struct.unpack(">II", data[16:24])
    return int(width), int(height)


def _load(name: str, cid: str) -> MailImage | None:
    path = IMAGE_DIR / name
    try:
        data = path.read_bytes()
    except OSError:
        return None
    width, height = _png_size(data)
    return MailImage(
        cid=cid,
        filename=name,
        data=data,
        width=round(width / SCALE),
        height=round(height / SCALE),
    )


@cache
def wordmark() -> MailImage | None:
    return _load("wordmark.png", WORDMARK_CID)


@cache
def headline(kind: str, lang: str) -> MailImage | None:
    """The hero for one letter in one language, or None if none was generated.

    None is a supported answer, not an error. A language added to
    domain/language.py before anyone has run the generator must still send —
    the layout falls back to live text in the Geist stack, which is what every
    letter did before these images existed. Failing the render instead would
    turn a typographic regression into an undelivered acknowledgement.
    """
    return _load(f"headline.{kind}.{lang}.png", HEADLINE_CID)


def for_letter(kind: str, lang: str) -> tuple[dict[str, object], tuple[MailImage, ...]]:
    """Everything the layout and the MIME builder need for one letter.

    Returns the template context and the parts to attach, always in step: an
    `<img>` whose CID is not attached shows a broken image, and an attached
    part no template references is dead weight in every inbox. One function
    returning both is what keeps them from drifting apart.
    """
    context: dict[str, object] = {}
    images: list[MailImage] = []
    for key, image in (("wordmark", wordmark()), ("headline", headline(kind, lang))):
        if image is None:
            continue
        context[f"{key}_cid"] = image.cid
        context[f"{key}_w"] = image.width
        context[f"{key}_h"] = image.height
        images.append(image)
    if "headline_cid" not in context:
        logger.info("mail.headline_image_missing", extra={"kind": kind, "lang": lang})
    return context, tuple(images)
