import "@testing-library/jest-dom/vitest";
import { render } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { RichText } from "../src/components/RichText";
import { generatedSectionKeys, isGeneratedSection } from "../src/lib/generatedSections";
import { parseRichText } from "../src/lib/richText";

// support.CERTAINTY_PHRASES in note-service (meeting_doc/support.py).
const CERTAINTY: Record<string, string[]> = {
  de: ["Voraussichtlich", "Schätzung", "Vorschlag", "Vorwurf", "Einschätzung"],
  en: ["Expected", "Estimate", "Proposal", "Allegation", "Opinion"],
  uk: ["Очікувано", "Оцінка", "Пропозиція", "Звинувачення", "Думка"],
};

function avatars(container: HTMLElement): number {
  return container.querySelectorAll(".speaker-avatar").length;
}

describe("generated text never renders as a speaker turn (SQ3 T1)", () => {
  for (const [language, phrases] of Object.entries(CERTAINTY)) {
    for (const phrase of phrases) {
      it(`${language} "${phrase}" opening a paragraph or a bullet keeps its letters`, () => {
        // The engine's new dash form is safe on any client.
        const dash = render(<RichText text={`${phrase} — Iran griff 2023 an.`} />);
        expect(avatars(dash.container)).toBe(0);
        expect(dash.container.textContent).toBe(`${phrase} — Iran griff 2023 an.`);
        dash.unmount();
        // The old colon form, inside a generated section: text, not a turn.
        const colon = render(<RichText text={`${phrase}: Iran griff 2023 an.`} allowSpeakerTurns={false} />);
        expect(avatars(colon.container)).toBe(0);
        expect(colon.container.textContent).toContain(`${phrase}: Iran griff`);
        expect(colon.container.textContent).not.toContain(`${phrase[0]}${phrase}`);
        colon.unmount();
        // A bullet is a list item: never a turn.
        const bullet = render(<RichText text={`- ${phrase}: Iran griff 2023 an.`} />);
        expect(avatars(bullet.container)).toBe(0);
        bullet.unmount();
      });
    }
  }

  it("an older note's 'Gast: X' paragraph renders as text in a generated section", () => {
    const { container } = render(
      <RichText text={"Podcast-Folge über Palantir.\n\nGast: Felix Holtermann"} allowSpeakerTurns={false} />,
    );
    expect(avatars(container)).toBe(0);
    expect(container.textContent).toContain("Gast: Felix Holtermann");
  });

  it("a line 'Anna: …' inside a generated section is text", () => {
    const [block] = parseRichText("Anna: we ship Friday", { speakerTurns: false });
    expect(block).toMatchObject({ kind: "para" });
    expect(block).not.toHaveProperty("speaker");
  });

  it("a transcript turn 'Anna: …' still gets its avatar", () => {
    const { container } = render(<RichText text="Anna: we ship Friday" />);
    expect(avatars(container)).toBe(1);
  });

  it("a section is generated by its key or by the generation's rows", () => {
    const keys = generatedSectionKeys([{ section_key: "decisions" }]);
    expect(isGeneratedSection("gen:overview", keys)).toBe(true);
    expect(isGeneratedSection("decisions", keys)).toBe(true);
    expect(isGeneratedSection("user_notes", keys)).toBe(false);
  });
});
