import "@testing-library/jest-dom/vitest";
import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { setSessionListener } from "../src/api/http";
import { SharedNotePage } from "../src/pages/SharedNotePage";

const TOKEN = "t".repeat(43);
const ITEM = { item_key: "k1", text: "Send proposal", owner_label: "Anna", due_date: null, due_text: null, status: "open", my_response: null, my_comment: null };
const BASE = {
  code: "N-1", title: "Kickoff", status: "draft", updated_at: "2026-09-12T10:00:00Z", issuer_name: "Acme",
  sections: [{ section_key: "decisions", name: "Decisions", text: "Go with B.", role: "decisions" }],
  sender: { issuer_name: "Acme", has_logo: false, logo_path: null, shared_by_display: "Anna" },
  product: { brand_name: "Klarnote", header_text: "Meeting summary generated by Klarnote.", cta_path: `/v1/shared/${TOKEN}/cta`, cta_enabled: true },
  expires_at: null, items: [ITEM], my_flags: [], can_respond: false, requires_verification: true, lang: "en", changes: null,
};

function stub(pages: Record<string, unknown>) {
  const calls: { method: string; path: string; body: { code?: string; reason?: string } | null }[] = [];
  vi.stubGlobal("fetch", vi.fn(async (url: unknown, init?: RequestInit) => {
    const path = new URL(String(url)).pathname;
    const method = (init?.method ?? "GET").toUpperCase();
    calls.push({ method, path, body: init?.body ? JSON.parse(String(init.body)) : null });
    const body = pages[`${method} ${path}`] ?? { status: "accepted" };
    return new Response(JSON.stringify(body), { status: 200, headers: { "Content-Type": "application/json" } });
  }));
  return calls;
}

function page() {
  return render(<MemoryRouter initialEntries={[`/s/${TOKEN}`]}><Routes><Route path="/s/:token" element={<SharedNotePage />} /></Routes></MemoryRouter>);
}

beforeEach(() => setSessionListener({}));
afterEach(() => vi.unstubAllGlobals());

describe("shared page — Sprint 23", () => {
  it("hides actions behind the verification gate and unlocks after the code", async () => {
    const calls = stub({
      [`GET /v1/shared/${TOKEN}`]: BASE,
      [`POST /v1/shared/${TOKEN}/verify`]: { ...BASE, requires_verification: false, can_respond: true },
    });
    page();
    expect(await screen.findByText("Verify it's you")).toBeInTheDocument();
    expect(screen.queryByRole("button", { name: /^confirm$/i })).not.toBeInTheDocument();
    await userEvent.click(screen.getByRole("button", { name: /send me a code/i }));
    await userEvent.type(await screen.findByLabelText(/^code$/i), "123456");
    await userEvent.click(screen.getByRole("button", { name: /^confirm$/i }));
    await waitFor(() => expect(calls.some((c) => c.path.endsWith("/verify") && c.body?.code === "123456")).toBe(true));
    expect(await screen.findByRole("button", { name: /^confirm$/i, hidden: false })).toBeInTheDocument();
    expect(document.documentElement.lang).toBe("en");
  });

  it("shows the changes strip and highlights the section", async () => {
    stub({ [`GET /v1/shared/${TOKEN}`]: { ...BASE, requires_verification: false, changes: { since_version: 1, sections_changed: ["decisions"], items_added: [], items_removed: [], items_changed: ["k1"] } } });
    page();
    expect(await screen.findByText(/Updated since you last looked/)).toBeInTheDocument();
    expect(document.querySelectorAll(".changed").length).toBe(2);
    await userEvent.click(screen.getByRole("button", { name: /dismiss/i }));
    expect(document.querySelectorAll(".changed").length).toBe(0);
  });

  it("hides the product line when a paid workspace turned it off, and reports a page", async () => {
    const calls = stub({ [`GET /v1/shared/${TOKEN}`]: { ...BASE, requires_verification: false, product: { ...BASE.product, cta_enabled: false } } });
    page();
    await screen.findByText("Kickoff");
    expect(screen.queryByRole("link", { name: /create your own workspace/i })).not.toBeInTheDocument();
    await userEvent.click(screen.getByRole("button", { name: /report this page/i }));
    await userEvent.click(screen.getByRole("button", { name: /inaccurate/i }));
    await waitFor(() => expect(calls.find((c) => c.path.endsWith("/report"))?.body).toEqual({ reason: "inaccurate" }));
  });

  it("speaks the note's language", async () => {
    stub({ [`GET /v1/shared/${TOKEN}`]: { ...BASE, requires_verification: false, lang: "uk" } });
    page();
    expect(await screen.findByText("Про що домовилися")).toBeInTheDocument();
    expect(document.documentElement.lang).toBe("uk");
  });
});
