import "@testing-library/jest-dom/vitest";
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { setSessionListener } from "../src/api/http";
import { SharedNotePage } from "../src/pages/SharedNotePage";

/**
 * The Shared Outcome Page (Sprint 19): what an outsider holding a link
 * sees. Sections land in a fixed order regardless of template order, the
 * product CTA is a plain server link, and a dead link is still a
 * touchpoint — the CTA stays.
 */

const TOKEN = "t".repeat(43);

const VIEW = {
  code: "N-2026-0001",
  title: "Kickoff: Website relaunch",
  status: "draft",
  updated_at: "2026-09-12T10:00:00Z",
  issuer_name: "Acme Consulting",
  sections: [
    { section_key: "discussion", name: "Discussion", text: "Long chat.", role: "other" },
    { section_key: "action_items", name: "Action items", text: "Send proposal — Anna", role: "action_items" },
    { section_key: "attendees", name: "Attendees", text: "Anna, Tom", role: "attendees" },
    { section_key: "decisions", name: "Decisions", text: "Go with option B.", role: "decisions" },
  ],
  sender: { issuer_name: "Acme Consulting", has_logo: false, logo_path: null, shared_by_display: "Anna" },
  product: {
    brand_name: "Klarnote",
    header_text: "Meeting summary generated by Klarnote. Create your own workspace free.",
    cta_path: `/v1/shared/${TOKEN}/cta`,
  },
  expires_at: "2026-12-11T10:00:00Z",
  items: [],
  my_flags: [],
  can_respond: true,
};

function stub(status: number, body: unknown) {
  const calls: string[] = [];
  vi.stubGlobal(
    "fetch",
    vi.fn(async (url: unknown) => {
      calls.push(new URL(String(url)).pathname);
      return new Response(JSON.stringify(body), {
        status,
        headers: { "Content-Type": "application/json" },
      });
    }),
  );
  return calls;
}

function page() {
  return render(
    <MemoryRouter initialEntries={[`/s/${TOKEN}`]}>
      <Routes>
        <Route path="/s/:token" element={<SharedNotePage />} />
      </Routes>
    </MemoryRouter>,
  );
}

beforeEach(() => setSessionListener({}));
afterEach(() => vi.unstubAllGlobals());

describe("shared outcome page", () => {
  it("renders sender, product header, and sections in the fixed order", async () => {
    const calls = stub(200, VIEW);
    page();
    expect(await screen.findByText("Acme Consulting")).toBeInTheDocument();
    expect(screen.getByText(/generated by Klarnote/)).toBeInTheDocument();

    const cta = screen.getByRole("link", { name: /create your own workspace/i });
    expect(cta.getAttribute("href")).toContain(`/v1/shared/${TOKEN}/cta`);

    const headings = screen.getAllByRole("heading", { level: 2 }).map((h) => h.textContent);
    expect(headings).toEqual(["What we agreed", "Who does what", "Discussion"]);
    expect(screen.getByText(/Shared by Anna via Klarnote/)).toBeInTheDocument();
    expect(document.title).toBe("Kickoff: Website relaunch — Acme Consulting");
    // The page asks for the note and nothing else — no /auth/refresh.
    expect(calls).toEqual([`/v1/shared/${TOKEN}`]);
  });

  it("puts the transcript behind its own tab, opened first when there are no notes", async () => {
    const transcript = "Speaker 1: Willkommen zum Auftakt.\n\nSpeaker 2: Danke.";
    stub(200, {
      ...VIEW,
      sections: [{ section_key: "attendees", name: "Attendees", text: transcript, role: "transcript" }],
    });
    page();
    expect(await screen.findByRole("tab", { name: "Transcript" })).toHaveAttribute("aria-selected", "true");
    expect(screen.getByText("Speaker 1")).toHaveClass("rt-speaker");
    expect(screen.getByText("Willkommen zum Auftakt.")).toBeInTheDocument();
    expect(screen.queryByRole("heading", { level: 2 })).toBeNull();
    await userEvent.click(screen.getByRole("tab", { name: "Notes" }));
    expect(screen.getByText(/No notes yet/)).toBeInTheDocument();
    expect(screen.queryByText("Speaker 1")).toBeNull();
  });

  it("opens on the notes when there are some, with the transcript one tab away", async () => {
    stub(200, {
      ...VIEW,
      sections: [...VIEW.sections, { section_key: "discussion2", name: "Discussion", text: "Anna: hi.\n\nTom: hi.", role: "transcript" }],
    });
    page();
    expect(await screen.findByRole("tab", { name: "Notes" })).toHaveAttribute("aria-selected", "true");
    expect(screen.getByRole("heading", { level: 2, name: "What we agreed" })).toBeInTheDocument();
    expect(screen.queryByText("Anna")).toBeNull();
  });

  it("shows a long roster as a section", async () => {
    const roster = "Anna Koval — CEO\nTom Client — buyer\nMax — engineering lead, joined late and left early after the demo";
    stub(200, { ...VIEW, sections: [{ section_key: "attendees", name: "Attendees", text: roster, role: "attendees" }] });
    page();
    expect(await screen.findByRole("heading", { level: 2, name: "Attendees" })).toBeInTheDocument();
    expect(screen.queryByRole("tab")).toBeNull();
  });

  it("keeps the CTA on a dead link", async () => {
    stub(404, { detail: "this link is not valid any more" });
    page();
    expect(await screen.findByText("This link is no longer valid.")).toBeInTheDocument();
    expect(screen.getByRole("link", { name: /create your own workspace/i })).toBeInTheDocument();
  });
});
