import "@testing-library/jest-dom/vitest";
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { setSessionListener } from "../src/api/http";
import { SharedNotePage } from "../src/pages/SharedNotePage";

/** The shared page: fixed section order, plain server-link CTA, and the CTA stays on a dead link. */

const TOKEN = "t".repeat(43);

const VIEW = {
  code: "N-2026-0001",
  title: "Kickoff: Website relaunch",
  status: "draft",
  updated_at: "2026-09-12T10:00:00Z",
  issuer_name: "Acme Consulting",
  sections: [
    { section_key: "discussion", name: "Discussion", text: "Long chat.", role: "other" },
    { section_key: "action_items", name: "Action items", text: "Send proposal — Anna", role: "action_items" },
    { section_key: "attendees", name: "Attendees", text: "Anna, Tom", role: "attendees" },
    { section_key: "decisions", name: "Decisions", text: "Go with option B.", role: "decisions" },
  ],
  sender: { issuer_name: "Acme Consulting", has_logo: false, logo_path: null, shared_by_display: "Anna" },
  product: {
    brand_name: "Klarnote",
    header_text: "Meeting summary generated by Klarnote.",
    cta_path: `/v1/shared/${TOKEN}/cta`,
  },
  expires_at: "2026-12-11T10:00:00Z",
  items: [],
  my_flags: [],
  can_respond: true,
};

function stub(status: number, body: unknown) {
  const calls: string[] = [];
  vi.stubGlobal(
    "fetch",
    vi.fn(async (url: unknown) => {
      calls.push(new URL(String(url)).pathname);
      return new Response(JSON.stringify(body), {
        status,
        headers: { "Content-Type": "application/json" },
      });
    }),
  );
  return calls;
}

function page() {
  return render(
    <MemoryRouter initialEntries={[`/s/${TOKEN}`]}>
      <Routes>
        <Route path="/s/:token" element={<SharedNotePage />} />
      </Routes>
    </MemoryRouter>,
  );
}

beforeEach(() => setSessionListener({}));
afterEach(() => vi.unstubAllGlobals());

describe("shared outcome page", () => {
  it("renders sender, product header, and sections in the fixed order", async () => {
    const calls = stub(200, VIEW);
    page();
    expect(await screen.findByText("Acme Consulting")).toBeInTheDocument();
    expect(screen.getByText(/generated by Klarnote/)).toBeInTheDocument();

    const cta = screen.getByRole("link", { name: /create your own workspace/i });
    expect(cta.getAttribute("href")).toContain(`/v1/shared/${TOKEN}/cta`);

    const headings = screen.getAllByRole("heading", { level: 2 }).map((h) => h.textContent);
    expect(headings).toEqual(["What we agreed", "Who does what", "Discussion"]);
    expect(screen.getByText(/Shared by Anna via Klarnote/)).toBeInTheDocument();
    expect(document.title).toBe("Kickoff: Website relaunch — Acme Consulting");
    // The page asks for the note and nothing else — no /auth/refresh.
    expect(calls).toEqual([`/v1/shared/${TOKEN}`]);
  });

  it("puts the transcript behind its own tab, opened first when there are no notes", async () => {
    const transcript = "Speaker 1: Willkommen zum Auftakt.\n\nSpeaker 2: Danke.";
    stub(200, {
      ...VIEW,
      sections: [{ section_key: "attendees", name: "Attendees", text: transcript, role: "transcript" }],
    });
    page();
    expect(await screen.findByRole("tab", { name: "Transcript" })).toHaveAttribute("aria-selected", "true");
    expect(screen.getByText("Speaker 1")).toHaveClass("rt-speaker");
    expect(screen.getByText("Willkommen zum Auftakt.")).toBeInTheDocument();
    expect(screen.queryByRole("heading", { level: 2 })).toBeNull();
    await userEvent.click(screen.getByRole("tab", { name: "Notes" }));
    expect(screen.getByText(/No notes yet/)).toBeInTheDocument();
    expect(screen.queryByText("Speaker 1")).toBeNull();
  });

  it("says the notes are still being written while the writer works, instead of 'empty'", async () => {
    stub(200, { ...VIEW, sections: [], preparing: true });
    page();
    expect(await screen.findByRole("status")).toHaveTextContent(/still being written/);
    expect(screen.queryByText("This note is empty.")).toBeNull();
  });

  it("says a note with nothing shareable is empty once the writer is done", async () => {
    stub(200, { ...VIEW, sections: [], preparing: false });
    page();
    expect(await screen.findByText("This note is empty.")).toBeInTheDocument();
  });

  it("opens on the notes when there are some, with the transcript one tab away", async () => {
    stub(200, {
      ...VIEW,
      sections: [...VIEW.sections, { section_key: "discussion2", name: "Discussion", text: "Anna: hi.\n\nTom: hi.", role: "transcript" }],
    });
    page();
    expect(await screen.findByRole("tab", { name: "Notes" })).toHaveAttribute("aria-selected", "true");
    expect(screen.getByRole("heading", { level: 2, name: "What we agreed" })).toBeInTheDocument();
    expect(screen.queryByText("Anna")).toBeNull();
  });

  it("shows a long roster as a section", async () => {
    const roster = "Anna Koval — CEO\nTom Client — buyer\nMax — engineering lead, joined late and left early after the demo";
    stub(200, { ...VIEW, sections: [{ section_key: "attendees", name: "Attendees", text: roster, role: "attendees" }] });
    page();
    expect(await screen.findByRole("heading", { level: 2, name: "Attendees" })).toBeInTheDocument();
    expect(screen.queryByRole("tab")).toBeNull();
  });

  it("keeps the CTA on a dead link", async () => {
    stub(404, { detail: "this link is not valid any more" });
    page();
    expect(await screen.findByText("This link is no longer valid.")).toBeInTheDocument();
    expect(screen.getByRole("link", { name: /create your own workspace/i })).toBeInTheDocument();
  });

  it("asks for the e-mailed code in six boxes, sends it when complete, and says it worked", async () => {
    const bodies: Record<string, unknown> = {
      [`/v1/shared/${TOKEN}`]: { ...VIEW, requires_verification: true },
      [`/v1/shared/${TOKEN}/verify/request`]: {},
      [`/v1/shared/${TOKEN}/verify`]: { ...VIEW, requires_verification: false },
    };
    const sent: string[] = [];
    vi.stubGlobal(
      "fetch",
      vi.fn(async (url: unknown, init?: RequestInit) => {
        const path = new URL(String(url)).pathname;
        if (init?.body) sent.push(String(init.body));
        return new Response(JSON.stringify(bodies[path] ?? {}), {
          status: path.endsWith("/verify/request") ? 202 : 200,
          headers: { "Content-Type": "application/json" },
        });
      }),
    );
    page();
    await userEvent.click(await screen.findByRole("button", { name: "Send me a code" }));
    expect(await screen.findByText(/We sent a 6-digit code/)).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Send a new code" })).toBeInTheDocument();

    const first = screen.getAllByRole("textbox")[0]!;
    await userEvent.click(first);
    await userEvent.paste("123456");
    expect(await screen.findByText(/Verified/)).toBeInTheDocument();
    expect(sent.some((b) => b.includes("123456"))).toBe(true);
    expect(screen.queryByText("Verify it's you")).toBeNull();
  });
});
