DROP FUNCTION IF EXISTS jobs_waiting_by_backend();
DROP FUNCTION IF EXISTS jobs_reap_stale_leases(DOUBLE PRECISION);
DROP FUNCTION IF EXISTS jobs_claim(TEXT[], TEXT, INTEGER, INTEGER);
DROP TABLE IF EXISTS jobs;
