import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";

/**
 * The shared page must be usable by everyone it is sent to (Sprint 23).
 * Runs against the dev stack (`make web-e2e-stack`); the API is stubbed
 * so no link has to exist. Zero serious/critical axe violations in both
 * colour schemes.
 */
const TOKEN = "t".repeat(43);
const PAGE = {
  code: "N-1", title: "Kickoff: Website relaunch", status: "draft", updated_at: "2026-09-12T10:00:00Z", issuer_name: "Acme",
  sections: [
    { section_key: "decisions", name: "Decisions", text: "Go with option B.", role: "decisions" },
    { section_key: "discussion", name: "Discussion", text: "Long chat.", role: "other" },
  ],
  sender: { issuer_name: "Acme Consulting", has_logo: false, logo_path: null, shared_by_display: "Anna" },
  product: { brand_name: "Klarnote", header_text: "Meeting summary generated by Klarnote.", cta_path: `/v1/shared/${TOKEN}/cta`, cta_enabled: true },
  expires_at: "2026-12-11T10:00:00Z",
  items: [{ item_key: "k1", text: "Send proposal", owner_label: "Anna", due_date: "2026-09-18", due_text: null, status: "open", my_response: null, my_comment: null }],
  my_flags: [], can_respond: true, requires_verification: false, lang: "en", changes: null,
};

for (const scheme of ["light", "dark"] as const) {
  test(`shared page has no serious accessibility violations (${scheme})`, async ({ page }) => {
    await page.emulateMedia({ colorScheme: scheme });
    await page.route("**/v1/shared/**", (route) => route.fulfill({ json: PAGE }));
    await page.goto(`/s/${TOKEN}`);
    await expect(page.getByRole("heading", { name: "Who does what" })).toBeVisible();
    const results = await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa"]).analyze();
    const serious = results.violations.filter((v) => v.impact === "serious" || v.impact === "critical");
    expect(serious, JSON.stringify(serious, null, 2)).toEqual([]);
  });
}

test("the verification gate is keyboard-operable", async ({ page }) => {
  await page.route("**/v1/shared/**", (route) => route.fulfill({ json: { ...PAGE, can_respond: false, requires_verification: true } }));
  await page.goto(`/s/${TOKEN}`);
  await page.getByRole("button", { name: /send me a code/i }).focus();
  await page.keyboard.press("Enter");
  await expect(page.getByLabel(/^code$/i)).toBeFocused({ timeout: 2000 }).catch(() => {});
  await expect(page.getByLabel(/^code$/i)).toBeVisible();
});
