"""Sending a recipient link from the product (Sprint 22, migration 0039).

Inline, through the SMTP adapter ``/share/email`` already uses: the
request renders, sends, records the outcome on the link row and
answers. No outbox, no worker, no share URL at rest — a slow relay costs
the sender a few seconds (bounded by ``share_email_timeout_s``), which
is the same trade sprint 16 made and documented for the other route.

What the mail says: who shared (display name + workspace), when the link
expires, the product line, an unsubscribe link — and nothing from the
note. No title, no section text. The recipient learns what was agreed
by opening the page, where the sender's own trust gate applies.

Opt-out is global and hashed: ``sha256(pepper || lower(email))`` is the
only thing stored, and a suppressed address is refused at send time
with a 409 the sender can act on (copy the link by hand).
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import logging
from dataclasses import dataclass
from datetime import UTC, datetime
from uuid import UUID

from fastapi import HTTPException, status

from ratelimit import FixedWindowLimiter

from ..adapters import share_mail, share_mail_copy
from ..adapters.email import EmailPermanentError, EmailProvider, OutboundEmail
from ..config import settings
from ..share_metrics import recipient_mail_sent
from . import notes_repository as repo

logger = logging.getLogger(__name__)

MAX_PERSONAL_MESSAGE = 300
UNSUBSCRIBE_PATH = "/v1/shared/unsubscribe"


# ── hashing + the unsubscribe signature ───────────────────────────────


def email_hash(email: str) -> bytes:
    pepper = bytes.fromhex(settings.share_mail_suppression_pepper_hex)
    return hashlib.sha256(pepper + email.strip().lower().encode("utf-8")).digest()


def _sig(link_id: UUID) -> str:
    key = bytes.fromhex(settings.share_link_hmac_key_hex)
    return hmac.new(key, b"unsub:" + link_id.bytes, hashlib.sha256).hexdigest()[:32]


def unsubscribe_token(link_id: UUID) -> str:
    """``<base64url(link id)>.<hmac>`` — no address anywhere in the URL;
    the server reads it from the link row."""
    payload = base64.urlsafe_b64encode(link_id.bytes).rstrip(b"=").decode("ascii")
    return f"{payload}.{_sig(link_id)}"


def verify_unsubscribe_token(token: str) -> UUID | None:
    payload, _, sig = token.partition(".")
    if not payload or not sig:
        return None
    try:
        raw = base64.urlsafe_b64decode(payload + "=" * (-len(payload) % 4))
        link_id = UUID(bytes=raw)
    except (ValueError, TypeError):
        return None
    if not hmac.compare_digest(sig, _sig(link_id)):
        return None
    return link_id


def unsubscribe_url(link_id: UUID) -> str:
    return (
        f"{settings.api_public_base_url.rstrip('/')}{UNSUBSCRIBE_PATH}/{unsubscribe_token(link_id)}"
    )


# ── caps ─────────────────────────────────────────────────────────────


class ShareMailCaps:
    """Per link, per sender, per workspace — each stopping a different
    abuse. Fail-open like the other note-service limiters; the tenant
    cap is the one that keeps the endpoint from being a relay."""

    def __init__(self, redis: object) -> None:
        self._limiter = FixedWindowLimiter(redis, prefix="note:share-mail")

    async def check(self, *, link_id: UUID, user_sub: UUID, tenant_id: UUID) -> None:
        day = 86_400
        for scope, subject, limit in (
            ("link", str(link_id), settings.share_mail_link_per_day),
            ("user", str(user_sub), settings.share_mail_user_per_day),
            ("tenant", str(tenant_id), settings.share_mail_tenant_per_day),
        ):
            decision = await self._limiter.allow(
                scope, subject, limit=limit, window_seconds=day, fail_open=True
            )
            if not decision.allowed:
                raise HTTPException(
                    status.HTTP_429_TOO_MANY_REQUESTS,
                    detail={
                        "code": "share_mail_cap",
                        "detail": f"the {scope} send limit for today is reached",
                        "scope": scope,
                        "limit": limit,
                    },
                    headers={"Retry-After": str(decision.retry_after)},
                )


# ── sending ──────────────────────────────────────────────────────────


@dataclass(frozen=True, slots=True)
class SendOutcome:
    status: str  # sent | failed
    error_class: str = ""


def _brand_line(lang: str) -> str:
    brand = settings.product_brand_name
    return {
        "de": f"Besprechungsnotizen, erstellt mit {brand}.",
        "uk": f"Підсумок зустрічі створено в {brand}.",
    }.get(lang, f"Meeting summary generated by {brand}.")


async def send_link(
    provider: EmailProvider,
    *,
    link: repo.ShareLinkRow,
    to_address: str,
    sharer_name: str,
    reply_to: str,
    issuer_name: str,
    personal_message: str,
    lang: str,
) -> SendOutcome:
    """Render and deliver one recipient-link mail. Never raises."""
    lang = share_mail_copy.normalize_lang(lang)
    share_url = f"{settings.app_base_url.rstrip('/')}/s/{repo_token(link)}"
    expires_on = (
        share_mail_copy.format_datetime(link.expires_at, lang).split(",")[0]
        if link.expires_at
        else ""
    )
    rendered = share_mail.render(
        lang=lang,
        sharer_name=sharer_name,
        sharer_email="",
        # Deliberately empty: the mail carries no note title (ADR-0031).
        note_title="",
        message=personal_message[:MAX_PERSONAL_MESSAGE],
        link_url=share_url,
        access=share_mail_copy.ACCESS_LINK,
        shared_at=datetime.now(UTC),
        issuer_name=issuer_name,
        expires_on=expires_on,
        brand_line=_brand_line(lang),
        unsubscribe_url=unsubscribe_url(link.id),
    )
    try:
        await provider.send(
            OutboundEmail(
                to_address=to_address,
                subject=rendered.subject,
                text_body=rendered.text_body,
                html_body=rendered.html_body,
                reply_to=reply_to,
            )
        )
    except EmailPermanentError as exc:
        recipient_mail_sent.add(1, {"outcome": "rejected"})
        logger.warning("note.recipient_mail.rejected", extra={"link_id": str(link.id)})
        return SendOutcome(status="failed", error_class=type(exc).__name__)
    except Exception as exc:  # noqa: BLE001 — the outcome is the answer
        recipient_mail_sent.add(1, {"outcome": "failed"})
        logger.error(
            "note.recipient_mail.send_failed",
            extra={"link_id": str(link.id), "error_class": type(exc).__name__},
        )
        return SendOutcome(status="failed", error_class=type(exc).__name__)
    recipient_mail_sent.add(1, {"outcome": "sent"})
    return SendOutcome(status="sent")


def repo_token(link: repo.ShareLinkRow) -> str:
    from .share_tokens import token_for

    return token_for(link.id, key_hex=settings.share_link_hmac_key_hex)


# ── Sprint 23: the verification code ─────────────────────────────────


def otp_hash(code: str, link_id: UUID) -> bytes:
    pepper = bytes.fromhex(settings.share_mail_suppression_pepper_hex)
    return hashlib.sha256(pepper + link_id.bytes + code.encode("ascii")).digest()


_OTP_COPY = {
    "en": ("Your code to respond: {code}", "Enter this code on the shared page to confirm it is you: {code}\n\nIt expires in 10 minutes. If you did not ask for it, ignore this mail."),
    "de": ("Ihr Code zum Antworten: {code}", "Geben Sie diesen Code auf der geteilten Seite ein: {code}\n\nEr läuft in 10 Minuten ab. Falls Sie ihn nicht angefordert haben, ignorieren Sie diese Mail."),
    "uk": ("Ваш код для відповіді: {code}", "Введіть цей код на сторінці нотатки: {code}\n\nВін дійсний 10 хвилин. Якщо ви його не запитували, проігноруйте цей лист."),
}  # fmt: skip


async def send_otp(provider: EmailProvider, *, to_address: str, code: str, lang: str) -> bool:
    """Text-only, no link: the recipient already has the page open."""
    lang = share_mail_copy.normalize_lang(lang)
    subject, body = _OTP_COPY.get(lang, _OTP_COPY["en"])
    try:
        await provider.send(
            OutboundEmail(
                to_address=to_address,
                subject=subject.format(code=code),
                text_body=body.format(code=code) + "\n\n" + share_mail_copy.LEGAL_LINE,
            )
        )
    except Exception as exc:  # noqa: BLE001 — the request answers 202 either way
        logger.warning("note.recipient_otp.send_failed", extra={"error_class": type(exc).__name__})
        return False
    return True
