"""Patient documents repository — RLS-scoped SQL over ``patient_documents``.

Metadata only. The file's bytes live in MinIO as ciphertext
(``storage_uri``); nothing in this module ever holds plaintext.
"""

from __future__ import annotations

from typing import Any
from uuid import UUID

import asyncpg

_COLUMNS = """
    id, tenant_id, patient_id, filename, category, note,
    content_type, byte_size, sha256, storage_uri,
    uploaded_by, created_at
"""


async def create_document(
    conn: asyncpg.Connection,
    *,
    document_id: UUID,
    tenant_id: UUID,
    patient_id: UUID,
    filename: str,
    category: str,
    note: str,
    content_type: str,
    byte_size: int,
    sha256: str,
    storage_uri: str,
    envelope_metadata: str,
    uploaded_by: UUID,
) -> asyncpg.Record:
    """Insert the metadata row for an already-uploaded object.

    ``document_id`` is generated by the caller because the envelope AAD binds
    to it before the object is written — same ordering as patients/ІПН.
    """
    return await conn.fetchrow(
        f"""
        INSERT INTO patient_documents
            (id, tenant_id, patient_id, filename, category, note,
             content_type, byte_size, sha256, storage_uri,
             envelope_metadata, uploaded_by)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11::jsonb, $12)
        RETURNING {_COLUMNS}
        """,
        document_id,
        tenant_id,
        patient_id,
        filename,
        category,
        note,
        content_type,
        byte_size,
        sha256,
        storage_uri,
        envelope_metadata,
        uploaded_by,
    )


async def list_documents(
    conn: asyncpg.Connection, *, patient_id: UUID, limit: int = 200
) -> list[asyncpg.Record]:
    return list(
        await conn.fetch(
            f"""
            SELECT {_COLUMNS} FROM patient_documents
            WHERE patient_id = $1
            ORDER BY created_at DESC, id
            LIMIT $2
            """,
            patient_id,
            limit,
        )
    )


async def get_document(
    conn: asyncpg.Connection, *, document_id: UUID, patient_id: UUID
) -> asyncpg.Record | None:
    """One row, scoped to its patient so a valid id from another record
    cannot be read through this patient's URL."""
    return await conn.fetchrow(
        f"SELECT {_COLUMNS} FROM patient_documents WHERE id = $1 AND patient_id = $2",
        document_id,
        patient_id,
    )


async def delete_document(
    conn: asyncpg.Connection, *, document_id: UUID, patient_id: UUID
) -> bool:
    """Drop the metadata row. The caller deletes the object FIRST — a row
    pointing at nothing is recoverable bookkeeping; an object nobody points
    at is PHI nobody can find to erase."""
    row: Any = await conn.fetchrow(
        "DELETE FROM patient_documents WHERE id = $1 AND patient_id = $2 RETURNING id",
        document_id,
        patient_id,
    )
    return row is not None


async def count_documents(conn: asyncpg.Connection, *, patient_id: UUID) -> int:
    return int(
        await conn.fetchval(
            "SELECT count(*) FROM patient_documents WHERE patient_id = $1", patient_id
        )
        or 0
    )
