"""Patients repository — RLS-scoped SQL over ``patients``.

Every function receives a connection already bound to ``app.tenant_id`` via
:func:`db.tenant_connection`; Postgres RLS enforces the tenant scope, so these
queries never spell out ``WHERE tenant_id = …`` for isolation (only for the
INSERT value).
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Any
from uuid import UUID

import asyncpg

_COLUMNS = """
    id, tenant_id, name_uk, name_en, dob, sex, mrn,
    phone, email,
    address_street, address_house, address_zip, address_city, address_country,
    summary_uk, summary_en, tags, status, last_visit_at,
    created_by, created_at, updated_at,
    (ipn_hmac IS NOT NULL) AS has_ipn, erased_at
"""


async def create_patient(
    conn: asyncpg.Connection,
    *,
    patient_id: UUID,
    tenant_id: UUID,
    created_by: UUID,
    name_uk: str,
    name_en: str,
    dob: date | None,
    sex: str,
    mrn: str,
    phone: str,
    email: str,
    address_street: str,
    address_house: str,
    address_zip: str,
    address_city: str,
    address_country: str,
    summary_uk: str,
    summary_en: str,
    tags: list[str],
    ipn_hmac: bytes | None = None,
    ipn_encrypted: bytes | None = None,
    ipn_dek: bytes | None = None,
) -> asyncpg.Record:
    """Insert a patient. ``patient_id`` is generated by the caller (not the
    DB default) because the raw-ІПН envelope binds its AAD to the row id
    before the INSERT runs."""
    return await conn.fetchrow(
        f"""
        INSERT INTO patients
            (id, tenant_id, name_uk, name_en, dob, sex, mrn,
             phone, email,
             address_street, address_house, address_zip,
             address_city, address_country,
             summary_uk, summary_en, tags, created_by,
             ipn_hmac, ipn_encrypted, ipn_dek)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
                $15, $16, $17, $18, $19, $20, $21)
        RETURNING {_COLUMNS}
        """,
        patient_id,
        tenant_id,
        name_uk,
        name_en,
        dob,
        sex,
        mrn,
        phone,
        email,
        address_street,
        address_house,
        address_zip,
        address_city,
        address_country,
        summary_uk,
        summary_en,
        tags,
        created_by,
        ipn_hmac,
        ipn_encrypted,
        ipn_dek,
    )


async def get_patient(
    conn: asyncpg.Connection, *, patient_id: UUID
) -> asyncpg.Record | None:
    return await conn.fetchrow(
        f"SELECT {_COLUMNS} FROM patients WHERE id = $1",
        patient_id,
    )


async def list_patients(
    conn: asyncpg.Connection,
    *,
    query: str | None,
    limit: int,
    cursor: tuple[datetime, UUID] | None,
    ipn_hmac: bytes | None = None,
    include_erased: bool = False,
) -> list[asyncpg.Record]:
    """Roster page ordered by recency (``COALESCE(last_visit_at, created_at)``
    DESC, id DESC). Keyset-paginated; fetches ``limit + 1`` so the caller can
    detect a next page.

    Search dispatch: when the caller resolved the search string to an ІПН
    lookup token, ``ipn_hmac`` is set and the text predicate is skipped — the
    match is exact, never partial. Raw ІПН never appears in a predicate here.

    Erased patients are excluded by default; ``include_erased=True`` (router
    gates it to tenant_admin) surfaces the tombstones the erasure audit trail
    points at."""
    where: list[str] = []
    args: list[Any] = []
    if not include_erased:
        where.append("status <> 'erased'")
    if ipn_hmac is not None:
        args.append(ipn_hmac)
        where.append(f"ipn_hmac = ${len(args)}")
    elif query:
        args.append(f"%{query}%")
        where.append(
            f"(name_uk ILIKE ${len(args)} OR name_en ILIKE ${len(args)} "
            f"OR mrn ILIKE ${len(args)})"
        )
    if cursor is not None:
        args.append(cursor[0])
        args.append(cursor[1])
        where.append(
            f"(COALESCE(last_visit_at, created_at), id) < (${len(args) - 1}, ${len(args)})"
        )
    args.append(limit + 1)
    where_sql = ("WHERE " + " AND ".join(where)) if where else ""
    return list(
        await conn.fetch(
            f"""
            SELECT {_COLUMNS}
            FROM patients
            {where_sql}
            ORDER BY COALESCE(last_visit_at, created_at) DESC, id DESC
            LIMIT ${len(args)}
            """,
            *args,
        )
    )


async def update_patient(
    conn: asyncpg.Connection,
    *,
    patient_id: UUID,
    fields: dict[str, Any],
) -> asyncpg.Record | None:
    """Patch a whitelist of columns. ``fields`` keys must be column names;
    callers (the router) own the whitelist, never the request body."""
    if not fields:
        return await get_patient(conn, patient_id=patient_id)
    sets: list[str] = []
    args: list[Any] = []
    for col, val in fields.items():
        args.append(val)
        sets.append(f"{col} = ${len(args)}")
    args.append(patient_id)
    return await conn.fetchrow(
        f"""
        UPDATE patients
        SET {", ".join(sets)}, updated_at = now()
        WHERE id = ${len(args)}
        RETURNING {_COLUMNS}
        """,
        *args,
    )


async def find_patient_id_by_ipn_hmac(
    conn: asyncpg.Connection, *, ipn_hmac: bytes
) -> UUID | None:
    """Id of the live (non-erased) patient carrying this ІПН token, if any.

    Used to enrich the duplicate-ІПН 409 so the FE can navigate to the
    existing record instead of creating a twin."""
    return await conn.fetchval(
        "SELECT id FROM patients WHERE ipn_hmac = $1 AND status <> 'erased'",
        ipn_hmac,
    )


async def find_patient_id_by_mrn(
    conn: asyncpg.Connection, *, mrn: str
) -> UUID | None:
    """Id of the live (non-erased) patient carrying this MRN, if any.

    The unique index is partial (``WHERE mrn <> ''``), so an empty MRN is
    "not assigned" and never matches — callers must not treat it as a key.
    """
    if not mrn:
        return None
    return await conn.fetchval(
        "SELECT id FROM patients WHERE mrn = $1 AND status <> 'erased'",
        mrn,
    )


async def bump_last_visit(
    conn: asyncpg.Connection, *, patient_id: UUID, when: datetime
) -> None:
    """Advance ``last_visit_at`` if ``when`` is newer (never moves it back)."""
    await conn.execute(
        """
        UPDATE patients
        SET last_visit_at = GREATEST(COALESCE(last_visit_at, $2), $2),
            updated_at = now()
        WHERE id = $1
        """,
        patient_id,
        when,
    )
